version: '3.9'
services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    container_name: django
    depends_on:
      postgres_mod:
        condition: service_healthy
    volumes:
      - ./static:/code/static/
      - ./media:/code/media/
    command: python3 manage.py runserver 0.0.0.0:8000

  postgres_mod:
    image: postgres:13
    container_name: postgres_mod
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    hostname: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      retries: 3
      interval: 10s
      timeout: 30s
    ports:
      - 5432:5432


volumes:
  postgres_data:
    driver: local
